apiVersion: v1
kind: Service
metadata:
  name: msyql-service
  namespace: production
spec: 
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targertPort: 3306
type: ClusterIP